# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'SmartPrompter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'GRDB.swift'
  pod 'Firebase'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'FirebaseUI/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Firebase/Messaging'


  # Pods for SmartPrompter

  target 'SmartPrompterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SmartPrompterUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
